### PR TITLE
frame buffer working

### PR DESCRIPTION
**Pull request by markfirmware**

### CODE REVIEW

**Comment by andrewrk** [comment]
Wow! This is really impressive, I never expected to get a pull request getting the frame buffer working. I tried this out with qemu and it works! I want to spend some time learning how this works when I merge it. Part of this project is a learning experience for me :)

**Comment by markfirmware** [comment]
This is key:
https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface

There is some generalization to do to go beyond the frame buffer. The mailbox code assumes only 32 bit arguments (the MAC address query uses [6]u8.)

**Comment by markfirmware** [comment]
This pr is now stable. I will open another that displays the zig logo and uses the font sheet from tetris to display the current time, etc.

**Comment by andrewrk** [comment]
Really neat! I'm looking forward to going over this in detail and doing some more work on this project. Thanks for your contribution.

**Pull request merged**
